
        <!-- Affichage du template lié à la vue -->
        <h2><i class="fa fa-star"></i> Commande payée</h2>

<h3>Merci d'avoir commandé au 3WA Restaurant !</h3>

<p data-order-step="success">Votre commande a bien été enregistrée, elle vous sera livrée dans les plus brefs délais.</p>
<p class="layout-center"><img alt="Commande payée" src="<?= $requestUrl ?>/stripe"></p>

<a class="button button-primary" href="<?= $requestUrl ?>/stripe?orderId=<?= $_GET['orderId'] ?>">Accueil</a>


