
        <!-- Affichage du template lié à la vue -->
        <h2><i class="fa fa-user"></i> Création d'un compte client</h2>

<form class="generic-form" action="<?= $requestUrl ?>/user" method="POST">

	

	<fieldset>
		<legend><i class="fa fa-book"></i> Identité et coordonnées</legend>
		<ul>
			<li>
				<label for="lastName">Nom :</label>
				<input id="lastName" type="text" name="lastName" data-required="" data-name="Nom" value="">
				<!--input id="lastName" type="text" name="lastName" value=""-->
			</li>
			<li>
				<label for="firstName">Prénom :</label>
				<input id="firstName" type="text" name="firstName" data-required="" data-name="Prénom" value="">
			</li>
			<li>
				<label for="birthDay">Date de naissance :</label>
				<select id="birthDay" name="birthDay">
					<?php
						$var = 31;
						for ($i=1; $i <= $var; $i++){?>
						<option value="<?=$i?>"><?=$i?></option><?php

						}
					?>

				</select>
				<span> / </span>
				<select name="birthMonth">
					<option value="1">Janvier</option>
					<option value="2">Février</option>
					<option value="3">Mars</option>
					<option value="4">Avril</option>
					<option value="5">Mai</option>
					<option value="6">Juin</option>
					<option value="7">Juillet</option>
					<option value="8">Août</option>
					<option value="9">Septembre</option>
					<option value="10">Octobre</option>
					<option value="11">Novembre</option>
					<option value="12">Décembre</option>
				</select>
				<span> / </span>
				<select name="birthYear">
					<?php
						$var = 2010;
						for ($i=1940; $i <= $var; $i++){?>
						<option value="<?=$i?>"><?=$i?></option><?php

						}
					?>



				</select>
			</li>
			<li>
				<label class="textarea" for="address">Adresse :</label>
				<textarea id="address" name="address" rows="3"></textarea>
			</li>
			<li>
				<label for="city">Ville :</label>
				<input id="city" type="text" name="city" value="">
			</li>
			<li>
				<label for="zipCode">Code Postal :</label>
				<input id="zipCode" class="zip-code" type="text" maxlength="5" name="zipCode" data-name="Code postal" data-type="number" value="">
			</li>
			<li>
				<label>Pays</label>
				<select name="country">
					<option value="URSS">URSS</option>
					<option value="Espagne">Espagne</option>
					<option value="Italie">Italie</option>
					<option value="Portos">Portos</option>
					<option value="Japan">Japan</option>
					<option value="China">China</option>
					<option value="leNord">Le Nord</option>
					<option value="Belgique">Belgique</option>
					<option value="Bretagne">Bretagne</option>
					<option value="Corse">Corse</option>
					<option value="USA">USA</option>
					<option value="Canada">Canada</option>
					<option value="Norvege">Norvege</option>
					<option value="france">France</option>

				</select>
			</li>
			<li>
				<label for="phone">Téléphone :</label>
				<input id="phone" class="phone" type="text" maxlength="10" name="phone" data-name="Téléphone" data-type="number" value="">
			</li>
		</ul>
	</fieldset>

	<fieldset>
		<legend><i class="fa fa-lock"></i> Informations d'authentification</legend>
		<ul>
	        <li>
	            <label for="email">E-mail :</label>
	            <input id="email" type="text" name="email" data-required="" data-name="E-mail" value="">
	        </li>
	        <li>
	            <label for="password">Mot de passe :</label>
	            <input id="password" type="password" name="password" data-required="" data-name="Mot de passe" data-length="8">
	        </li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Créer le compte">
			<a class="button button-cancel small" href="/dev/Restaurant (corrigé)/index.php">Annuler</a>
		</li>
	</ul>
</form>    