<main>
        
<h2><i class="fa fa-pencil"></i> Editer un article</h2>

<form class="generic-form" action="edit_post.php?id=<?=$_GET['id']?>" method="post">
    <input type="hidden" name="postId" value="<?= intval($_GET['id']) ?>">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title" value="<?=$EditArticle[0]['Title']?>">
            </li>
            <li>
                <label class="textarea" for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="15"><?= $EditArticle[0]['Content'] ?></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Mettre à jour</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>    </main>