<!DOCTYPE html>
<html lang="fr"><head>
    <meta charset="utf-8">
    <title>Encore un Blog ?! #nonMaisAllo</title>

    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <!-- En-tête commune de l'application -->
    <header class="blog-header">
        <h1><a href="index.php"><i class="fa fa-microphone"></i> Encore un Blog ?! #nonMaisAllo</a></h1>
     


        <nav>

        <?php if(array_key_exists('user', $_SESSION) == false) { ?>
            <a href="register.php"><i class="fas fa-save"></i> Enregistrement</a>
            <a href="login.php"><i class="fas fa-sign-in-alt"></i> Login</a>
            <?php } else { ?>
            <a href="admin.php"><i class="fa fa-cogs">
            </i> Administration</a>
            <a href="logout.php"><i class="fas fa-sign-out-alt"></i> Logout</a>
            <p><?=$_SESSION['user']['FirstName']?>     <?= $_SESSION['user']['LastName']?>  
            <a href="info.php">  (info)</a></p>
            <?php } ?>

        </nav>
    </header>

    <main>
        
         <?php include $template.'.phtml' ?>
    </main>

    <!-- Pied de page commun de l'application -->
    <footer class="blog-footer">
        <small>Le blog des élèves de la 3W Academy</small>
    </footer>

</body></html>