<form class="generic-form" id="register-form" action="register.php" method="POST">
	<fieldset>
	<legend><i class="fa fa-sticky-note-o"></i> Enregistrement</legend>
		<ul>
			<li>
				<label>Nom</label>
			    <input type="text" name="LastName"/>
		    </li>
		    <li>
			    <label>Prénom</label>
			    <input type="text" name="FirstName"/>
		    </li>
		    <li>
			    <label>Email</label>
			    <input type="text" name="Email"/>
		    </li>
		    <li>
			    <label>Password</label>
			    <input type="Password" name="Password"/>
		    </li>
		    <li>

		    	<input class="button button-primary" type="submit" value="envoyer"/>
		    </li>
		</ul>
	</fieldset>
</form>



