<main>

    <h2><i class="fa fa-file-text-o"></i> Article</h2>

    <!-- Article du blog -->
    <section class="post">
        <h3><?= $ShowPost[0]['Title']?> </h3>
        <article><?= $ShowPost[0]['Content']?> </article>
        <small>rédigé par <?=$ShowPost[0]['FirstName']?> <?=$ShowPost[0]['LastName']?> le <?= $ShowPost[0]['CreationTimesTamp'] ?></small>
    </section>

    <hr>

    <!-- Liste des commentaires de l'article du blog -->
    <ul class="comment-list">
    <?php foreach ($ShowComment as $key => $Comment) { ?>
                <li class="comment">

                <h4><i class="fa fa-comment"><?=$Comment['NickName']?></i>
                </h4>
                <article>
                    <?=$Comment['Content']?>
                </article>
            </li>
            <?php }?>
        </ul>

    <hr>

    <form class="generic-form" action="add_comment.php" method="POST">

        <input type="hidden" name="postId" value="<?=$ShowPost[0]['Id']?>">

        <fieldset>
            <legend><i class="fa fa-comment-o"></i> Nouveau commentaire</legend>
            <ul>
                <li>
                    <label for="nickName">Pseudo :</label>
                    <input type="text" id="nickName" name="nickName">
                </li>
                <li>
                    <label class="textarea" for="contents">Commentaire :</label>
                    <textarea id="contents" name="contents" rows="5"></textarea>
                </li>
                <li>
                    <button class="button button-primary" type="submit">Ajouter</button>
                    <a class="button button-cancel" href="index.php">Annuler</a>
                </li>
            </ul>
        </fieldset>
    </form>    
</main>