<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->


<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <?php  foreach ($meals as $key => $meal) { ?>
        	<tr>
        		<td><img src="<?= $wwwUrl ?>/images/meals/<?= $meal['Photo']; ?>" alt="<?= $meal['Name']; ?>"></td>
        		<td class="middle">
        			<h2><?= $meal['Name'] ?></h2>
        			<p><?= $meal['Description'] ?></p>
        		</td>
        		<td class="number"><strong><?= number_format($meal['SalePrice'], 2) ?></strong> €</td>
       <?php } ?>
    </tbody>
</table>