
<div class="container">
	<h2 class="my-4 text-center">Faut payer maintenant</h2>
	<form action="<?=$requestUrl?>/order/stripe?orderId=<?=$_GET['orderId']?>" method="post" id="payment-form">
		<div class="form-row">
			 <input type="text" class="form-control mb-3 StripeElement StripeElemen--empty" placeHolder="Prénom" name="first_name">

			 <input type="text" class="form-control mb-3 StripeElement StripeElemen--empty" placeHolder="Nom" name="last_name">


			<div id="card-element" class="form-control ">
			      <!-- A Stripe Element will be inserted here. -->
		</div>

			    <!-- Used to display form errors. -->
		<div id="card-errors" role="alert"></div>
			  </div>

		<button class="button button-primary">Submit Payment</button>
		<a class="button button-cancel" href="<?= $requestUrl ?>/delete?orderId=<?=$_GET['orderId']?>">Annuler</a>
	</form>
</div>
		
<script src="https://js.stripe.com/v3/"></script>
<script src="<?=$wwwUrl?>/js/charge.js"></script>	